### PR TITLE
updated readme and get started

### PR DESCRIPTION
**Pull request by latlio**

### CODE REVIEW

**Review by dsrobertson — CHANGES_REQUESTED** [review]
Looking at the .md file there's still some residual output for some reason - is it possible to remove that?

**Comment by latlio** [comment]
> Looking at the .md file there's still some residual output for some reason - is it possible to remove that?

specifying message=FALSE and warning=FALSE in rmarkdown chunk doesn't seem to remove that since I think the output is actual output as opposed to messages or warnings. I could suppress it more strictly with invisible() but I don't know of any other ways to suppress it.

**Comment by dsrobertson** [comment]
> specifying message=FALSE and warning=FALSE in rmarkdown chunk doesn't seem to remove that since I think the output is actual output as opposed to messages or warnings. I could suppress it more strictly with invisible() but I don't know of any other ways to suppress it.

How about if you specify include=FALSE?

**Comment by latlio** [comment]
> How about if you specify include=FALSE?

When I tried that, it didn't display the code chunk either

**Comment by dsrobertson** [comment]
> When I tried that, it didn't display the code chunk either

Ok how about including results=FALSE

**Review by dsrobertson — APPROVED** [review]

**Pull request merged**
