### PR TITLE
Automating BiocCheck testing and website building

### PR DESCRIPTION
**Pull request by pc494**
### BiocCheck testing

Fairly self-explanatory, this runs the relevant tests (ie. the one BioConductor requires that CRAN would not) as a separate sub-workflow to `R cmd check`

### Website building

Ideally, the website would rebuild everytime a PR was merged. This would mean that API changes get filed into the documentation as they come in. **Currently broken** but will use this PR as a place to gather thoughts before fixing locally.

### CODE REVIEW

**Comment by pc494** [comment]
You can see the website failure here:
https://github.com/pc494/onlineFDR/runs/5250883704?check_suite_focus=true

It appears to be looking for the `setBound` topic in the index and not finding it.

**Comment by dsrobertson** [comment]
Thanks Phillip! Regarding the website failure, I think that adding `@keywords internal` to the `setBound` function should solve the issue (see https://blog.r-hub.io/2019/12/12/internal-functions/#how-to-document-internal-functions)

**Comment by pc494** [comment]
Thanks @dsrobertson, I wouldn't have thought to look there, I will have another go.

**Comment by pc494** [comment]
Okay, I had been running this on my fork as well, I think having tried all the suggested fiddlings the easiest option is just to add `SetBound` to the index in the 'Other' section. Apologies for all the notifications, I thought this would be plain sailing but alas.

UPDATE: That worked (see https://github.com/pc494/onlineFDR/pull/6) - I'll make a separate PR if you consider that a good solution to the problem

**Comment by dsrobertson** [comment]
Thanks for looking into this! Sure, happy for `SetBound` to be added to the index in the 'Other' section as a solution.

**Pull request closed without merging**
